### PR TITLE
Extend forms config to be its own object

### PR DESCRIPTION
**Pull request by xylo04**
@rainerg2000, before your PR goes live, I'd like to make a breaking change to the config object. This is so we can keep track of the last poll time and only poll, say, daily. @martinhpedersen, happy for your comments, too.

### CODE REVIEW

**Review by rainerg2000 — APPROVED** [review]
Looks good.

**Comment by martinhpedersen** [comment]
@xylo04 - It's not perfectly clear to me what you intent to do with `LastUpdateCheck`, but it suggests keeping some app state that is programmatically updated. Please correct me if I'm wrong.

As a general rule of thumb, I think it's best to avoid keeping app state in the config file. I would prefer keeping it in a separate (hidden) file under the same directory. That way we avoid cluttering the user-defined configuration, and avoid having to rewrite the file which might lead to unintended side-effects (the file might contain user-defined attributes).

Have a look at this approach for a similar use case, where we store the state in a separate file:
https://github.com/la5nta/pat/blob/69eaf703972d89bbd9c697e9b2662006f6616955/version_report.go#L24-L36

**Comment by xylo04** [comment]
@martinhpedersen yes, that was going to be my approach. I didn't see other examples of it in Pat, but I did see that there's a `WriteConfig` method so thought it might be reasonable. But yes, I can plan to store state elsewhere, thanks for the pointer.

Might as well revert this commit and keep `forms_path` as-is.

**Comment by martinhpedersen** [comment]
@xylo04 - I can see how you would think that. But WriteConfig will remove any attributes that are not defined in the Config-struct. E.g. if someone have something like this in their file:

```json
{
  "mycall": "LA5NTA",
  "_comment": "My precious comment",
  "locator": ...
}
```

It might also re-order the attributes, and other rarities.

Maybe not a common thing, but it is nice to avoid re-writing the config if we can 😄 I've tried to avoid it as much as possible, and really only used it as a last resort when we needed to upgrade existing user configurations due to important changes.

**Pull request merged**
